"""Builds docs/ml_results.md from reports/ and models/metadata.json.

Every number in that file is read from a generated artefact; nothing is typed by hand. Pieces
that have not been produced yet are marked pending, with the command that produces them.
Run from the repo root: python -m pipeline.report
"""
import json
import time
from pathlib import Path

import pandas as pd

from pipeline import features
from pipeline.settings import MODELS_DIR, REPORTS_DIR, ROOT, get_logger, risk_bands

log = get_logger(__name__)
OUT = ROOT / "docs" / "ml_results.md"
ARCHIVE = "archive/split_sample_v1"
DISCRIMINATION = [("roc_auc", "ROC-AUC"), ("brier", "Brier")]
CLASSIFICATION = [("accuracy", "Accuracy"), ("precision", "Precision"), ("recall", "Sensitivity"),
                  ("specificity", "Specificity"), ("f1", "F1")]


class Artefacts:
    """Read-only access to generated files. Missing files return None."""

    def __init__(self, reports_dir=REPORTS_DIR, models_dir=MODELS_DIR):
        self.reports, self.models = Path(reports_dir), Path(models_dir)

    def json(self, name, models=False):
        path = (self.models if models else self.reports) / name
        return json.loads(path.read_text(encoding="utf-8")) if path.exists() else None

    def csv(self, name):
        path = self.reports / name
        return pd.read_csv(path) if path.exists() else None

    def pngs(self):
        return sorted(p.name for p in self.reports.glob("*.png")) if self.reports.exists() else []

    def meta(self):
        return self.json("metadata.json", models=True)

    def summary(self):
        """The final-evaluation summary, whichever protocol produced it."""
        return self.json("validation_summary.json") or self.json("holdout_summary.json")

    def performance(self):
        """{target: {metric: (estimate, lo, hi)}} from the final evaluation, plus a label for it."""
        cv = self.csv("performance_metrics.csv")
        if cv is not None:
            return {t: {r.metric: (r.estimate, r.lo, r.hi) for r in d.itertuples()}
                    for t, d in cv.groupby("target", sort=False)}, "cross-validated"
        ho = self.csv("holdout_metrics.csv")
        if ho is not None:
            return {t: {r.metric: (r.holdout, r.holdout_lo, r.holdout_hi) for r in d.itertuples()}
                    for t, d in ho.groupby("target", sort=False)}, "holdout"
        return None, None


def num(v, d=3) -> str:
    try:
        v = float(v)
    except (TypeError, ValueError):
        return "n/a"
    return "n/a" if v != v else f"{v:.{d}f}"


def with_ci(v, ci, d=3) -> str:
    return f"{num(v, d)} [{num(ci[0], d)}, {num(ci[1], d)}]" if ci else num(v, d)


def triple(t, d=2) -> str:
    return with_ci(t[0], (t[1], t[2]), d)


def pct(v) -> str:
    try:
        return f"{100 * float(v):.1f}%"
    except (TypeError, ValueError):
        return "n/a"


def span(r) -> str:
    return "none" if not r else f"{r[0]:.2f} to {r[1]:.2f}"


def table(head, rows) -> list:
    out = ["| " + " | ".join(head) + " |", "|" + "|".join("---" for _ in head) + "|"]
    return out + ["| " + " | ".join(str(c) for c in r) + " |" for r in rows] + [""]


def label(name) -> str:
    from pipeline.external import DERIVED_LABELS
    return features.by_name().get(name, {}).get("label") or DERIVED_LABELS.get(name, name)


def pending(step, when="") -> list:
    return [f"_Pending: run `python -m pipeline {step}`{' ' + when if when else ''}._", ""]


def s_header(a) -> list:
    meta, lock = a.meta(), a.json("holdout_lock.json")
    lines = ["# RiskAtlas: ML results", "",
             "> Generated by `python -m pipeline.report`. Do not edit by hand: every number below is read "
             "from `reports/` or `models/metadata.json`. Re-run the pipeline, then this report, to update it.", ""]
    facts = [f"Report generated: {time.strftime('%Y-%m-%d %H:%M')}"]
    if meta:
        sha = meta["git_sha"]
        version = sha[:10] + (" (with uncommitted changes)" if sha.endswith("-dirty") else "")
        protocol = meta.get("protocol", "holdout")
        facts += [f"Validation protocol: **{protocol}**"
                  + (" (models developed on all patients; performance from cross-validation of the whole "
                     "procedure)" if protocol == "full_cv" else " (locked holdout)"),
                  f"Models trained: {meta['created']} on {meta.get('n_patients', 'n/a')} patients",
                  f"Code version: `{version}`", f"Data SHA-256: `{meta['data_sha256'][:12]}`"]
    if lock:
        facts.append(f"Original holdout opened for {lock['distinct_model_sets_evaluated']} model set(s); "
                     "see section 13")
    return lines + [f"- {f}" for f in facts] + [""]


def s_data(a) -> list:
    lines = ["## 1. Data", ""]
    audit = a.json("data_audit.json")
    if not audit:
        return lines + pending("audit")
    dropped = ", ".join(audit["dropped_features"]) or "none"
    lines += [f"Extension of Z-Alizadeh Sani: **{audit['n_patients']} patients**, "
              f"{audit['n_features_active']} model inputs ({audit['n_features_defined']} defined; dropped: {dropped}). "
              f"Missing cells in the raw file: {audit['raw_missing_cells']}. "
              f"Duplicate patient rows: {audit['duplicate_patient_rows']}.", ""]
    lines += table(["Target", "Positive"], [[t, pct(v["all"])] for t, v in audit["prevalence"].items()])
    for t, c in audit["label_consistency"].items():
        if t == "vessel_count_distribution":
            continue
        lines += [f"{t} is defined as at least 50% narrowing in any vessel, and the labels agree with that for "
                  f"almost every patient. Exceptions: labelled {t} without a stenotic vessel: "
                  f"{c['positive_without_stenotic_vessel']}; stenotic vessel without a {t} label: "
                  f"{c['stenotic_vessel_without_positive']}. Both kept as recorded.", ""]
    flags = audit["flags"]
    rare = ", ".join(label(n) for n in flags["near_constant"]) or "none"
    lines += [f"Rare binary features (minority class under the audit threshold; kept, regularised models "
              f"handle them): {rare}.", ""]
    table_ = a.csv("data_audit_features.csv")
    if flags["out_of_range"] and table_ is not None:
        t = table_.set_index("feature")
        medians = "; ".join(f"{label(n)} median {num(t.at[n, 'median'], 1)} {t.at[n, 'unit']} against "
                            f"{num(t.at[n, 'range_low'], 1)}-{num(t.at[n, 'range_high'], 1)}"
                            for n in flags["out_of_range"])
        lines += [f"Mostly outside their adult reference range: {medians}. The medians are plausible for a "
                  "cardiac referral cohort, so this reflects the population rather than a unit error.", ""]
    return lines + ["Per-feature detail: `reports/data_audit_features.csv`.", ""]


def s_selection(a) -> list:
    lines = ["## 2. Model selection", ""]
    meta = a.meta()
    if not meta:
        return lines + pending("train")
    fams = list(next(iter(meta["targets"].values()))["dev_cv"])
    lines += ["Mean ROC-AUC per model family from repeated cross-validation on all development patients, "
              "corrected standard error in brackets. The chosen family is the simplest one within one standard "
              "error of the best (one-SE rule). Vessel models are conditional on CAD by design: "
              "P(vessel) = P(CAD) × P(vessel | CAD), so a vessel can never look riskier than CAD itself. "
              "The last column shows how often each family was chosen when the whole procedure was rerun "
              "inside the outer cross-validation folds, a check on how stable the choice is.", ""]
    rows = []
    for t, m in meta["targets"].items():
        choices = ", ".join(f"{f} {n}" for f, n in sorted((m.get("procedure_family_choices") or {}).items(),
                                                           key=lambda kv: -kv[1])) or "n/a"
        structure = "direct" if m.get("kind", "direct") == "direct" else f"given {m['parent']}"
        rows.append([t, structure, *[f"{num(m['dev_cv'][f]['auc'])} ({num(m['dev_cv'][f]['se'])})" for f in fams],
                     f"**{m['family']}**", choices])
    return lines + table(["Target", "Structure", *fams, "Chosen", "Chosen in outer folds"], rows)


def s_performance(a) -> list:
    lines = ["## 3. Headline performance", ""]
    perf, kind = a.performance()
    meta = a.meta()
    if perf is None:
        if not meta:
            return lines + pending("train")
        return lines + pending("evaluate")
    if kind == "cross-validated":
        lines += [a.summary()["notes"]["estimate"], "", "95% bootstrap intervals in brackets. "
                  + a.summary()["notes"]["classification"], ""]
    else:
        lines += ["**Holdout**: patients never used for training, model selection or thresholds. "
                  "95% bootstrap intervals in brackets.", ""]
    lines += table(["Target"] + [l for _, l in DISCRIMINATION],
                   [[t] + [triple(m[k]) for k, _ in DISCRIMINATION] for t, m in perf.items()])
    lines += table(["Target"] + [l for _, l in CLASSIFICATION],
                   [[t] + [triple(m[k]) for k, _ in CLASSIFICATION] for t, m in perf.items()])
    archived = a.csv(f"{ARCHIVE}/holdout_metrics.csv")
    if kind == "cross-validated" and meta:
        old = {t: d.set_index("metric") for t, d in archived.groupby("target")} if archived is not None else {}
        lines += ["The same models' ROC-AUC under the other estimates, for comparison. The original 61-patient "
                  "holdout (section 13) is far noisier; the development figure is optimistic because model "
                  "families were chosen on it.", ""]
        rows = []
        for t, m in perf.items():
            o = old.get(t)
            rows.append([t, triple(m["roc_auc"]),
                         with_ci(o.at["roc_auc", "holdout"], (o.at["roc_auc", "holdout_lo"], o.at["roc_auc", "holdout_hi"]), 2)
                         if o is not None else "n/a",
                         num(meta["targets"][t]["dev_oof"]["metrics"]["roc_auc"], 2)])
        lines += table(["Target", "Cross-validated (headline)", "Original holdout, v1 models",
                        "Development, optimistic"], rows)
    return lines


def s_thresholds(a) -> list:
    lines = ["## 4. Operating points and risk bands", ""]
    meta = a.meta()
    if not meta:
        return lines + pending("train")
    low, mid, high = (b["label"] for b in risk_bands())
    perf, kind = a.performance()
    lines += [f"Each target has its own cut points, chosen on cross-validated development predictions: "
              f"**{low}** below the rule-out point (95% sensitivity), **{high}** from the rule-in point "
              f"(90% specificity), **{mid}** in between. The decision threshold maximises Youden's J.", ""]
    col = f"{kind} sensitivity" if kind else "sensitivity"
    rows = [[t, pct(m["prevalence"]), num(m["threshold"]), num(m["rule_out"]), num(m["rule_in"]),
             pct(perf[t]["recall"][0]) if perf else "pending", pct(perf[t]["specificity"][0]) if perf else "pending"]
            for t, m in meta["targets"].items()]
    return lines + table(["Target", "Prevalence", "Threshold", "Rule-out below", "Rule-in from",
                          col.capitalize(), (f"{kind} specificity" if kind else "specificity").capitalize()], rows)


def s_calibration(a) -> list:
    lines = ["## 5. Calibration", ""]
    perf, kind = a.performance()
    if perf is None:
        return lines + pending("evaluate")
    lines += ["Probabilities are calibrated with Platt scaling inside every cross-validation fold. Lower Brier "
              "is better. ECE uses quantile bins and is noisy at this sample size; the plots in "
              "`reports/calibration_<target>.png` are more informative.", ""]
    rows = [[t, triple(m["brier"], 3), triple(m["ece"], 3)] for t, m in perf.items()]
    return lines + table(["Target", f"Brier ({kind})", f"ECE ({kind})"], rows)


def s_dca(a) -> list:
    lines = ["## 6. Clinical usefulness (decision curves)", ""]
    s = a.summary()
    if not s:
        return lines + pending("evaluate")
    lines += ["Net benefit weighs true positives against false positives at each threshold probability. The "
              "range below is where acting on the model beats both treating everyone and treating no one. "
              "Plot: `reports/decision_curve_validation.png`.", ""]
    rows = [[t, pct(d["prevalence"]), span(d["useful_threshold_range"])] for t, d in s["decision_curve"].items()]
    return lines + table(["Target", "Prevalence", "Useful threshold range"], rows)


def s_consistency(a) -> list:
    lines = ["## 7. Consistency between CAD and the vessels", ""]
    s = a.summary()
    if not s:
        return lines + pending("evaluate")
    lines += ["CAD means stenosis in at least one vessel, so P(CAD) should never sit below the riskiest "
              "vessel's probability. With vessels modelled as P(CAD) × P(vessel | CAD) this holds by "
              "construction; the check confirms it on held-out predictions.", ""]
    rows = [[t, num(c["tolerance"], 2), pct(c["share_below_top_vessel"]), num(c["max_gap"])]
            for t, c in s["consistency"].items()]
    return lines + table(["Overall target", "Tolerance", "Share of patients below top vessel", "Largest gap"], rows)


def s_subgroups(a) -> list:
    lines = ["## 8. Subgroups", ""]
    sg = a.csv("subgroups.csv")
    if sg is None:
        return lines + pending("evaluate")
    label_set = "procedure_cv" if "procedure_cv" in set(sg["set"]) else "holdout"
    lines += ["ROC-AUC by sex and age band, on held-out predictions. Read these as a check for large failures, "
              "not as precise estimates. Blank AUC means too few patients or one class only.", ""]
    d = sg[sg["set"] == label_set]
    rows = [[r.target, r.subgroup, r.level, int(r.n), int(r.n_pos), num(r.roc_auc)] for r in d.itertuples()]
    return lines + table(["Target", "Subgroup", "Level", "n", "Positive", "ROC-AUC"], rows)


def s_explanations(a) -> list:
    lines = ["## 9. Explanations", ""]
    meta = a.meta()
    if not meta or a.csv(f"shap_global_{next(iter(meta['targets']))}.csv") is None:
        return lines + pending("explain")
    k = 5
    lines += [f"Top {k} drivers by mean absolute SHAP value (probability scale). (+) means higher values push "
              "risk up, (−) down. Agreement is the mean share of the top 5 features that SHAP and LIME have in "
              "common across checked patients.", ""]
    rows = []
    for t in meta["targets"]:
        g, lime = a.csv(f"shap_global_{t}.csv"), a.csv(f"lime_check_{t}.csv")
        tops = []
        for r in g.head(k).itertuples():
            sign = "" if r.direction_corr != r.direction_corr else (" (+)" if r.direction_corr > 0 else " (−)")
            tops.append(f"{label(r.feature)}{sign}")
        rows.append([t, "; ".join(tops), num(lime["overlap_at_k"].mean(), 2) if lime is not None else "n/a"])
    return lines + table(["Target", "Top drivers", "SHAP–LIME agreement"], rows)


def s_uncertainty(a) -> list:
    lines = ["## 10. Per-prediction uncertainty", ""]
    unc = (a.summary() or {}).get("uncertainty")
    if not unc:
        return lines + pending("evaluate")
    lines += ["Each prediction carries a 10th–90th percentile interval from bootstrap refits. If the interval "
              "is informative, wider intervals go with larger errors (positive Spearman correlation) and the "
              "wide half of patients has the worse Brier score. Checked on held-out predictions.", ""]
    rows = [[t, u["n_bag"], num(u["median_width"]), f"{num(u['spearman_width_vs_error'], 2)} (p={num(u['p_value'], 3)})",
             num(u["brier_narrow_half"]), num(u["brier_wide_half"])] for t, u in unc.items()]
    return lines + table(["Target", "Bag size", "Median width", "Spearman width vs error", "Brier, narrow half",
                          "Brier, wide half"], rows)


def s_counterfactuals(a) -> list:
    lines = ["## 11. Counterfactuals", ""]
    cf = a.json("counterfactuals_summary.json")
    if not cf:
        return lines + pending("counterfactual")
    lines += ["For high-band patients: the smallest set of changes to mutable factors (at most a few) that moves "
              f"the patient below the rule-in point. {cf['note']}", ""]
    rows = []
    for t, s in cf["targets"].items():
        top = ", ".join(f"{m['label']} ({m['count']})" for m in s["most_changed"]) or "none"
        rows.append([t, s["n_high_band"], s["n_evaluated"], pct(s["achieved_share"]),
                     num(s["mean_changes_when_achieved"], 1), top])
    return lines + table(["Target", "High-band patients", "Evaluated", "Plausible change found",
                          "Mean changes", "Most changed"], rows)


def s_external(a) -> list:
    lines = ["## 12. External validation", ""]
    ext = a.json("external_validation.json")
    if not ext or "by_site" not in ext or "internal" not in ext:
        return lines + pending("external")
    feats = ", ".join(label(n) for n in ext["features"])
    lines += [f"Reduced-feature {ext['target']} model ({ext['family']}) using only the features both datasets share: "
              f"{feats}. Trained on the development data, then applied unchanged to the UCI Heart Disease "
              f"collection. {ext['note']}", ""]

    def row(name, s):
        if "metrics" not in s:
            return [name, s["n"], pct(s["prevalence"]), s.get("note", "n/a"), "", "", ""]
        m, ci = s["metrics"], s["ci"]
        return [name, s["n"], pct(s["prevalence"]), with_ci(m["roc_auc"], ci["roc_auc"], 2), num(m["brier"]),
                pct(m["recall"]), pct(m["specificity"])]

    rows = [row("Internal (out-of-fold)", ext["internal"]), row("External, all sites", ext["external"])]
    rows += [row(f"External: {s}", v) for s, v in ext["by_site"].items()]
    lines += table(["Cohort", "n", "Prevalence", "ROC-AUC [95% CI]", "Brier", "Sensitivity", "Specificity"], rows)
    cal = ext["external"]["calibration"]
    missing = {n: v for n, v in ext["missing_rate"]["all"].items() if v > 0}
    lines += ["Per-site AUCs are the fairer read: the pooled AUC compares patients across sites with very "
              "different prevalence, which can move it either way.", ""]
    lines += [f"External calibration slope {num(cal['slope'], 2)} and intercept {num(cal['intercept'], 2)} "
              "(1 and 0 are perfect; a slope below 1 means predictions are too extreme for this population). "
              f"Missing values imputed: {', '.join(f'{label(n)} {pct(v)}' for n, v in missing.items()) or 'none'}. "
              "Plot: `reports/calibration_external.png`.", ""]
    return lines


def s_archive(a) -> list:
    lines = ["## 13. Original split-sample check (superseded)", ""]
    old = a.csv(f"{ARCHIVE}/holdout_metrics.csv")
    if old is None:
        return lines + ["_No archived split-sample result._", ""]
    lock = a.json("holdout_lock.json")
    uses = lock["distinct_model_sets_evaluated"] if lock else "n/a"
    lines += [f"The first design held out 61 patients, locked, and scored them once with the first model set "
              f"(holdout opened for {uses} model set(s)). Those results are kept unchanged in "
              f"`reports/{ARCHIVE}/`. With about two dozen events per vessel, a single small holdout has very "
              "wide intervals and depends on which patients fall in it, so the project moved to developing on "
              "all patients with cross-validated performance (Steyerberg, J Clin Epidemiol 2018, recommends "
              "against random splitting in small samples). The change was made after this result was seen, "
              "which is why it is reported here in full.", ""]
    rows = []
    for t, d in old.groupby("target", sort=False):
        d = d.set_index("metric")
        rows.append([t, with_ci(d.at["roc_auc", "holdout"], (d.at["roc_auc", "holdout_lo"], d.at["roc_auc", "holdout_hi"]), 2),
                     with_ci(d.at["brier", "holdout"], (d.at["brier", "holdout_lo"], d.at["brier", "holdout_hi"]), 2)])
    return lines + table(["Target", "Holdout ROC-AUC (v1 models)", "Holdout Brier (v1 models)"], rows)


def s_experiments(a) -> list:
    lines = ["## 14. Model experiments", ""]
    exp = a.csv("experiments/model_comparison.csv")
    if exp is None:
        return lines + ["_Pending: run `python experiments/model_comparison.py`._", ""]
    lines += ["Approaches compared on the original 242-patient development set, all on identical repeated "
              "cross-validation folds, before the final design was chosen. TabPFN v2 is a pretrained "
              "foundation model for small tabular data (Hollmann et al., Nature 2025). It was not adopted: its "
              "gains are within noise, it is worse on RCA, and at several seconds per prediction on a CPU it "
              "would break real-time interaction in the 3D viewer. That a state-of-the-art model barely moves "
              "the result suggests the ceiling is the information in the features, not the model.", ""]
    wide = exp.pivot(index="approach", columns="target", values="auc")
    cols = [c for c in ["CAD", "LAD", "LCX", "RCA"] if c in wide.columns]
    rows = [[ap] + [num(wide.at[ap, c]) if pd.notna(wide.at[ap, c]) else "" for c in cols] for ap in wide.index]
    return lines + table(["Approach"] + cols, rows)


def s_latency(a) -> list:
    lines = ["## 15. Inference latency", ""]
    dev = a.json("dev_analysis.json")
    if not dev:
        return lines + pending("analysis")
    lat = dev["latency_ms_median"]
    return lines + [f"Median per request on the machine that ran the pipeline: full payload (probabilities, "
                    f"uncertainty, SHAP, counterfactuals) **{num(lat['full'], 0)} ms**; fast path for live sliders "
                    f"(probabilities and bands) **{num(lat['fast'], 0)} ms**.", ""]


def s_figures(a) -> list:
    pngs = a.pngs()
    return ["## 16. Figures", ""] + ([f"- `reports/{p}`" for p in pngs] or ["_None generated yet._"]) + [""]


SECTIONS = [s_header, s_data, s_selection, s_performance, s_thresholds, s_calibration, s_dca, s_consistency,
            s_subgroups, s_explanations, s_uncertainty, s_counterfactuals, s_external, s_archive, s_experiments,
            s_latency, s_figures]


def build(a: Artefacts) -> str:
    return "\n".join(line for section in SECTIONS for line in section(a)).rstrip() + "\n"


def run() -> Path:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build(Artefacts()), encoding="utf-8")
    log.info("wrote %s", OUT)
    return OUT


if __name__ == "__main__":
    run()
