// Generate web/viewer-demo/viewer-config.generated.json for the demo harness from the single sources of truth:
//   config/risk_bands.yaml   band ids, labels, colours (lowest risk first)
//   config/manifest.yaml     targets, mesh names, labels
//   models/metadata.json     per-target cut points rule_out / rule_in
// Band rule, as in pipeline/metrics.py: p < rule_out -> first band, p >= rule_in -> last band, otherwise the middle one.
// Nothing here is typed by hand. `--check` exits 1 if the committed file is stale.   Run: npm run bands

import { parse } from 'yaml';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, '../..');
const out = path.join(repo, 'web/viewer-demo/viewer-config.generated.json');
const read = (p) => fs.readFileSync(path.join(repo, p), 'utf8');
const sha = (s) => crypto.createHash('sha256').update(s).digest('hex').slice(0, 16);

const bandsSrc = read('config/risk_bands.yaml'), manifestSrc = read('config/manifest.yaml'), metaSrc = read('models/metadata.json');
const bands = parse(bandsSrc).bands;
const manifest = parse(manifestSrc);
const meta = JSON.parse(metaSrc);
if (bands.length !== 3) throw new Error(`risk_bands.yaml: expected exactly 3 bands, found ${bands.length}`);

const target = (name) => {
  const t = manifest.targets[name];
  const m = meta.targets[name];
  if (!m || m.rule_out === undefined || m.rule_in === undefined) throw new Error(`models/metadata.json has no rule_out/rule_in for ${name}`);
  return { id: t.mesh ?? name, target: name, label: t.label, mesh: t.mesh ?? null, rule_out: m.rule_out, rule_in: m.rule_in };
};
const targets = Object.keys(manifest.targets).map(target);

const doc = {
  note: 'GENERATED by web/scripts/gen_viewer_bands.mjs from config/ and models/metadata.json. Do not edit.',
  sources: { 'config/risk_bands.yaml': sha(bandsSrc), 'config/manifest.yaml': sha(manifestSrc), 'models/metadata.json': sha(metaSrc) },
  bands: bands.map((b) => ({ id: b.id, label: b.label, color: b.color })),
  vessels: targets.filter((t) => t.mesh),
  overall: targets.find((t) => !t.mesh) ?? null,
};
const text = JSON.stringify(doc, null, 2) + '\n';

if (process.argv.includes('--check')) {
  const have = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
  if (have !== text) { console.error('viewer-config.generated.json is stale: run `npm run bands` in web/scripts'); process.exit(1); }
  console.log('viewer-config.generated.json is up to date');
} else {
  fs.writeFileSync(out, text);
  console.log('wrote', path.relative(repo, out));
}
