import type { ApiProvider } from '../client';
import { ApiError } from '../errors';
import type { FeatureMeta, FullPrediction, Inputs, Meta, Predict, PredictMode, PhysiologyItem, TargetFull } from '../types';
import exampleFile from './example_prediction.json';
import metaFile from './meta.json';

// Client-side stand-in for the API. Both JSON files are generated by `npm run sync:mock` from reports/ and config/.
// The numbers are NOT predictions. Starting from the example payload, each feature's SHAP contribution is scaled by
// how far the entered value sits from the training median relative to the example patient, so sliders visibly move
// things. The UI flags every mock response ("MOCK DATA - not a real prediction").

export const mockMeta = metaFile as unknown as Meta;
const example = exampleFile as unknown as { input: Record<string, number>; output: FullPrediction };

const clamp = (x: number, lo: number, hi: number) => Math.min(hi, Math.max(lo, x));

function factor(f: FeatureMeta, x: number): number {
  const ex = example.input[f.name];
  if (ex === undefined) return 0;
  if (x === ex) return 1;
  const ref = f.stats?.median ?? ex;
  const den = ex - ref;
  const span = f.stats ? f.stats.max - f.stats.min || 1 : 1;
  if (Math.abs(den) < 1e-9 * span || Math.abs(den) < 0.02 * span) return x === ref ? 0 : x > ex ? 1.5 : 0.5;
  return clamp((x - ref) / den, -1, 2.5);
}

function bandFor(meta: Meta, t: { rule_out: number; rule_in: number }, p: number): string {
  const bands = meta.risk_bands;
  const i = p < t.rule_out ? 0 : p >= t.rule_in ? bands.length - 1 : Math.floor(bands.length / 2);
  return bands[i]!.id;
}

function physiology(meta: Meta, inputs: Inputs): Record<string, PhysiologyItem> {
  const out: Record<string, PhysiologyItem> = {};
  for (const f of meta.features) {
    if (!f.range) continue;
    const v = inputs[f.name];
    const value = v === undefined || v === null || Number.isNaN(v) ? null : v;
    const [lo, hi] = f.range;
    const status = value === null ? 'missing' : value < lo ? 'low' : value > hi ? 'high' : 'normal';
    out[f.name] = { label: f.label, value, unit: f.unit, range: [lo, hi], status };
  }
  return out;
}

/** Pure: same inputs, same output. Exported for tests. */
export function mockPredict<M extends PredictMode>(mode: M, inputs: Inputs, meta: Meta = mockMeta): Predict<M> {
  const src = example.output;
  const byName = new Map(meta.features.map((f) => [f.name, f]));
  const targets: Record<string, TargetFull> = {};

  for (const tm of meta.targets) {
    const ex = src.targets[tm.id];
    if (!ex) continue;
    const contributions: Record<string, number> = {};
    for (const [name, c0] of Object.entries(ex.shap.contributions)) {
      const f = byName.get(name);
      const x = inputs[name];
      contributions[name] = f && x !== undefined && x !== null ? c0 * factor(f, x) : 0;
    }
    // Keep additivity (base + sum == probability) while holding the probability inside (0.01, 0.99),
    // and a vessel never above its parent target (the real models are conditional on CAD).
    const cap = tm.conditional_on ? (targets[tm.conditional_on]?.probability ?? 0.99) : 0.99;
    const sum = Object.values(contributions).reduce((a, b) => a + b, 0);
    const raw = ex.shap.base + sum;
    const p = clamp(raw, 0.01, Math.min(0.99, cap));
    if (raw !== p && sum !== 0) {
      const k = (p - ex.shap.base) / sum;
      for (const n of Object.keys(contributions)) contributions[n] = contributions[n]! * k;
    }
    const shift = p - ex.probability;
    const used = Object.keys(inputs).filter((n) => inputs[n] !== null && inputs[n] !== undefined);
    const changes = ex.counterfactual.changes.filter((c) => inputs[c.feature] === c.from);
    const thresholds = { rule_out: ex.rule_out, rule_in: ex.rule_in };
    const band = bandFor(meta, thresholds, p);
    const needed = band === meta.risk_bands[meta.risk_bands.length - 1]!.id;
    targets[tm.id] = {
      probability: p,
      band,
      threshold: ex.threshold,
      rule_out: ex.rule_out,
      rule_in: ex.rule_in,
      uncertainty: {
        ...ex.uncertainty,
        low: clamp(ex.uncertainty.low + shift, 0, 1),
        high: clamp(ex.uncertainty.high + shift, 0, 1),
        // fewer entered features, wider interval
        width: ex.uncertainty.width * (1 + (1 - used.length / meta.features.length) * 0.5),
      },
      shap: { base: ex.shap.base, contributions },
      counterfactual: {
        ...ex.counterfactual,
        start: p,
        needed,
        achieved: needed && changes.length > 0 ? ex.counterfactual.achieved : !needed,
        end: needed && changes.length > 0 ? ex.counterfactual.end + shift : p,
        changes: needed ? changes : [],
      },
    };
  }

  const vessels = meta.targets.filter((t) => t.kind === 'vessel' && targets[t.id]);
  const top = vessels.reduce<string | null>((a, t) => (a === null || targets[t.id]!.probability > targets[a]!.probability ? t.id : a), null);
  const coherence: FullPrediction['coherence'] = {};
  for (const t of meta.targets) {
    if (t.kind !== 'overall' || !targets[t.id] || top === null) continue;
    const gap = targets[top]!.probability - targets[t.id]!.probability;
    coherence[t.id] = { top_vessel: top, gap, below_top_vessel: gap > 0 };
  }

  const names = meta.features.map((f) => f.name);
  const full: FullPrediction = {
    targets,
    coherence,
    physiology: physiology(meta, inputs),
    input: {
      missing: names.filter((n) => inputs[n] === undefined || inputs[n] === null),
      ignored: Object.keys(inputs).filter((k) => !byName.has(k)),
    },
    model: { created: 'mock', git_sha: 'mock' },
    timing_ms: { total: 0 },
    mock: true,
  };
  if (mode === 'full') return full as Predict<M>;
  const fast = { ...full, targets: {} as Record<string, unknown> };
  for (const [id, t] of Object.entries(targets)) {
    fast.targets[id] = { probability: t.probability, band: t.band, threshold: t.threshold, rule_out: t.rule_out, rule_in: t.rule_in };
  }
  return fast as unknown as Predict<M>;
}

export class MockProvider implements ApiProvider {
  readonly kind = 'mock' as const;
  constructor(private readonly latencyMs: { fast: number; full: number } = { fast: 60, full: 700 }) {}

  getMeta(): Promise<Meta> {
    return Promise.resolve(structuredClone(mockMeta));
  }

  predict<M extends PredictMode>(mode: M, inputs: Inputs, signal?: AbortSignal): Promise<Predict<M>> {
    // End-to-end tests install window.__riskatlasApiLog = [] to see which path each request took.
    (globalThis as { __riskatlasApiLog?: unknown[] }).__riskatlasApiLog?.push({ mode, at: Date.now() });
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => resolve(mockPredict(mode, inputs)), this.latencyMs[mode]);
      signal?.addEventListener(
        'abort',
        () => {
          clearTimeout(timer);
          reject(new ApiError('aborted', 'Request cancelled.'));
        },
        { once: true },
      );
      if (signal?.aborted) {
        clearTimeout(timer);
        reject(new ApiError('aborted', 'Request cancelled.'));
      }
    });
  }
}
